---
title: "Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

```{r}
data("rest_inspec")

rest_inspec =
  rest_inspec %>%
  select(boro, cuisine_description, score, grade, zipcode) %>%
  filter(
    boro == "MANHATTAN",
    grade == "A",
    zipcode %in% 10001:10010,
    cuisine_description %in% c("African", "American", "Asian", "English", "French", "Greek" , "Italian", "Japanese", "Korean", "Mexican", "Chicken", "German", "Russian", "Indian")) %>%
  drop_na(score)
```

Column {data-width=650}
-------------------------------------------------

### Chart A

```{r}
rest_inspec %>%
  mutate(
    text_label = str_c("cuisine: ", cuisine_description, "\nScore: ", score),
    cuisine_description = fct_reorder(cuisine_description, score)
    ) %>%
  plot_ly(
    x = ~cuisine_description, y = ~score, text = ~text_label, color = ~cuisine_description, alpha = 0.5, type = "box", colors = "viridis")
```

Column {data-width=350}
-------------------------------------------------

### Chart B
```{r}
rest_inspec %>%
  count(cuisine_description) %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>%
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar", colors = "viridis")
```

### Chart C
```{r}
rest_inspec %>%
  mutate(
    zipcode = as.character(zipcode)
  ) %>%
  plot_ly(
    x = ~cuisine_description, y = ~zipcode, color = ~cuisine_description, alpha = 0.5, type = "violin", colors = "viridis")
```

